application: goo-gly
version: 1
runtime: python
api_version: 1

#default_expiration: "1m"

handlers:
- url: /_wave/.*
  script: goo-gly.py

- url: /assets
  static_dir: assets

- url: /goo-gly_install.xml
  static_files: goo-gly_install.xml
  upload: goo-gly_install.xml

- url: /goo-gly_allmodes_install.xml
  static_files: goo-gly_allmodes_install.xml
  upload: goo-gly_allmodes_install.xml
